<script setup lang="ts">
// Visual header/footer configuration: edits the `page` object inside the
// template's defaults JSON (the shared components/page.typ partial reads
// it at render time). No hidden state — switching to the Defaults tab
// shows exactly what this form wrote.
import { computed } from 'vue'
import { useDesigner } from '../state/designer'

const designer = useDesigner()

const cfg = computed(() => designer.pageCfg)

function str(key: string): string {
  const v = cfg.value[key]
  return typeof v === 'string' ? v : ''
}

function onText(key: string, e: Event) {
  designer.setPage(key, (e.target as HTMLInputElement).value)
}

function onNumber(key: string, e: Event) {
  const n = Number((e.target as HTMLInputElement).value)
  if (Number.isFinite(n) && n > 0) designer.setPage(key, n)
}
</script>

<template>
  <div class="page-form">
    <div v-if="!designer.usesBranded" class="page-form-hint">
      <p>
        This template does not use the shared page component yet, so these
        settings have no effect on it.
      </p>
      <button class="btn btn-secondary" @click="designer.applyBrandedToSource()">
        Apply <code>components/page.typ</code> to source
      </button>
    </div>
    <span v-else class="tag tag-green">components/page.typ applied</span>

    <h6>Header</h6>
    <div class="row2">
      <div class="field">
        <label>Left</label>
        <input class="input" :value="str('header_left')" placeholder="e.g. ACME Corp"
          @input="onText('header_left', $event)" />
      </div>
      <div class="field">
        <label>Right</label>
        <input class="input" :value="str('header_right')" placeholder="e.g. Confidential"
          @input="onText('header_right', $event)" />
      </div>
    </div>

    <h6>Footer</h6>
    <div class="row2">
      <div class="field">
        <label>Left</label>
        <input class="input" :value="str('footer_left')" placeholder="e.g. generated by TypstPdf"
          @input="onText('footer_left', $event)" />
      </div>
      <div class="field">
        <label>Right</label>
        <input class="input" :value="str('footer_right')" placeholder="e.g. document ref"
          @input="onText('footer_right', $event)" />
      </div>
    </div>
    <label class="radio">
      <input
        type="checkbox"
        :checked="cfg.page_numbers !== false"
        @change="designer.setPage('page_numbers', ($event.target as HTMLInputElement).checked)"
      />
      <span class="dot" aria-hidden="true"></span>
      Page numbers (“Page N of M”, footer right)
    </label>

    <h6>Sheet</h6>
    <div class="row2">
      <div class="field">
        <label>Paper</label>
        <select
          class="input"
          :value="typeof cfg.paper === 'string' ? cfg.paper : 'a4'"
          @change="onText('paper', $event)"
        >
          <option value="a4">A4</option>
          <option value="us-letter">US Letter</option>
          <option value="us-legal">US Legal</option>
          <option value="a3">A3</option>
          <option value="a5">A5</option>
        </select>
      </div>
      <div class="field">
        <label>Margin (cm)</label>
        <input class="input" type="number" min="0.5" max="6" step="0.5"
          :value="typeof cfg.margin_cm === 'number' ? cfg.margin_cm : 2"
          @input="onNumber('margin_cm', $event)" />
      </div>
    </div>

    <p class="text-muted page-form-note">
      Stored as <code>page</code> in this template's defaults — overridable
      per request like any other payload key.
    </p>
  </div>
</template>
