// Contract note template — the Typst equivalent of Zerodha's move from
// HTML→Chrome→PDF, to LaTeX, to Typst. Typst compiles even huge
// trade tables in a fraction of LaTeX's time, from a single binary.
//
// The build harness drops a per-client `data.json` next to this file
// and runs `typst compile`.

#let d = json("data.json")

#set page(paper: "a4", margin: (x: 1.6cm, y: 1.4cm), footer: context [
  #set text(size: 8pt, fill: gray)
  #d.broker.name — Contract Note #d.note_no
  #h(1fr)
  Page #counter(page).display() of #counter(page).final().first()
])
#set text(font: "DejaVu Sans", size: 9pt)

// ---- Header ----------------------------------------------------------
#grid(
  columns: (1fr, auto),
  [
    #text(size: 16pt, weight: "bold", fill: rgb("#387ed1"))[#d.broker.name]
    #v(2pt)
    #text(size: 8pt, fill: gray)[
      #d.broker.address \
      SEBI Regn: #d.broker.sebi_regn
    ]
  ],
  align(right)[
    #text(size: 11pt, weight: "bold")[CONTRACT NOTE]
    #v(2pt)
    #text(size: 8pt)[
      Note No: #d.note_no \
      Trade date: #d.trade_date
    ]
  ],
)
#line(length: 100%, stroke: 0.5pt + gray)

// ---- Client ----------------------------------------------------------
#v(4pt)
#grid(
  columns: (1fr, 1fr),
  [
    *#d.client.name* \
    Client ID: #raw(d.client.id) \
    Email: #d.client.email
  ],
  align(right)[
    Settlement: #d.settlement \
    Generated: #d.generated_at
  ],
)
#v(6pt)

// ---- Trades table ----------------------------------------------------
#let money(v) = [₹#str(v)]

#table(
  columns: (auto, auto, auto, auto, 1fr, auto, auto, auto),
  align: (left, left, left, center, left, right, right, right),
  stroke: 0.4pt + gray.lighten(40%),
  fill: (_, y) => if y == 0 { rgb("#387ed1").lighten(85%) },
  table.header(
    [*Order No*], [*Time*], [*Exchange*], [*B/S*], [*Symbol*],
    [*Qty*], [*Price*], [*Value*],
  ),
  ..for t in d.trades {
    (
      raw(t.order_no), t.time, t.exchange,
      if t.side == "B" { text(fill: green.darken(20%))[BUY] }
      else { text(fill: red.darken(10%))[SELL] },
      t.symbol, str(t.qty), money(t.price), money(t.value),
    )
  },
)

// ---- Charges summary -------------------------------------------------
#v(8pt)
#align(right)[
  #table(
    columns: (auto, auto),
    align: (left, right),
    stroke: none,
    inset: (x: 8pt, y: 2.5pt),
    [Gross traded value], money(d.summary.gross),
    [Brokerage], money(d.summary.brokerage),
    [Exchange txn charges], money(d.summary.txn_charges),
    [STT], money(d.summary.stt),
    [GST], money(d.summary.gst),
    [SEBI fees + stamp duty], money(d.summary.other),
    table.hline(stroke: 0.6pt),
    [*Net amount #if d.summary.net_side == "payable" [payable] else [receivable]*],
    [*#money(d.summary.net)*],
  )
]

#v(10pt)
#text(size: 7.5pt, fill: gray)[
  This is a computer-generated contract note and is digitally signed; it
  does not require a physical signature. Sample document generated by a
  demo pipeline — not a real financial record.
]
